server:
  servlet:
    context-path: /bank/v1
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:account-db
    username: app
    password: 'app'
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format-sql: true
    show-sql: false

bank:
  grpc-server:
    port: 8182
  grpc-client:
    account-holder:
      host: localhost
      port: 8181