server:
  servlet:
    context-path: /bank/v1/customer
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:customer-db
    username: app
    password: 'app'
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format-sql: true
    show-sql: false