server:
  servlet:
    context-path: /bank/v1/account-holder
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:ah-db
    username: app
    password: 'app'
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format-sql: true
    show-sql: false

bank:
  grpc-server:
    port: 8181